<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 3.5.3 setup script
 * Date: Sun, 21 Oct 2012 19:56:38 -0500
 */

$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>